/*
 * Purpose:  Use tree-structured communication to find the global sum
 *           of a random collection of ints
 *
 * Compile:  mpicc -g -Wall -o ex2_tree_sum ex2_tree_sum.c
 * Run:      mpiexec -n <comm_sz> ./ex2_tree_sum
 *
 * Input:    None
 * Output:   Random values generated by processes, and their global sum.
 *
 * Note:     This version assumes comm_sz is a power of 2.
 */


#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>

int Global_sum(int my_int, int my_rank, int comm_sz, MPI_Comm comm);

const int MAX_CONTRIB = 20;

int main(void) {
   int i, sum, my_int;
   int my_rank, comm_sz;
   MPI_Comm comm;
   int* all_ints = NULL;

   MPI_Init(NULL, NULL);
   comm = MPI_COMM_WORLD;
   MPI_Comm_size(comm, &comm_sz);
   MPI_Comm_rank(comm, &my_rank);

   srandom(my_rank + 1);
   my_int = random() % MAX_CONTRIB;

   sum = Global_sum(my_int, my_rank, comm_sz, comm);

   if ( my_rank == 0) {
      all_ints = malloc(comm_sz*sizeof(int));
      MPI_Gather(&my_int, 1, MPI_INT, all_ints, 1, MPI_INT, 0, comm);
      printf("Ints being summed:\n   ");
      for (i = 0; i < comm_sz; i++)
         printf("%d ", all_ints[i]);
      printf("\n");
      printf("Sum = %d\n",sum);
      free(all_ints);
   } else {
      MPI_Gather(&my_int, 1, MPI_INT, all_ints, 1, MPI_INT, 0, comm);
   }

   MPI_Finalize();
   return 0;
}  /* main */

/*-------------------------------------------------------------------
 * Function:   Global_sum
 * Purpose:    Implement a global sum using tree-structured communication
 * Notes:
 * 1.  comm_sz must be a power of 2
 * 2.  The return value is only valid on process 0
 */
int Global_sum(
      int my_int    /* in */,
      int my_rank   /* in */,
      int comm_sz   /* in */,
      MPI_Comm comm /* in */) {
 int send_sum=my_int;//发送数据
 int n = 1;
 while (n < comm_sz) {
   int receive_flag=0;//是否接收过消息
   int send_flag=0;//是否发送过消息
   int receive_or_send_rank = my_rank ^ n; 
   if (my_rank < receive_or_send_rank&&receive_flag==0) {
      int received_sum;//接收数据
      MPI_Recv(&received_sum, 1, MPI_INT, receive_or_send_rank, 0, comm, MPI_STATUS_IGNORE);
      send_sum+= received_sum;
   } 
   else if(send_flag==0){
      send_flag=1;
      MPI_Send(&send_sum, 1, MPI_INT, receive_or_send_rank, 0, comm);
 }
 n*=2;
}
return send_sum;
}  /* Global_sum */
